/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Medicos;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis Felipe
 */
public class MostrarDatosMedicos extends javax.swing.JFrame {

    /**
     * Creates new form MostrarDatosMedicos
     */
    public MostrarDatosMedicos() {
        initComponents();
        this.getContentPane().setBackground(Color.lightGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Especialidad", "Prestador al IESS", "Codigo/R#._ Colegio de Medicos", "Fecha de Registro", "Lista de Seguros Medicos/Asociados", "Sueldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jButton1.setFont(new java.awt.Font("Felix Titling", 2, 24)); // NOI18N
        jButton1.setText("Cerrar ventana");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 1750, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1738, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(500, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(85, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         this.setVisible(false); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarDatosMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarDatosMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarDatosMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarDatosMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarDatosMedicos().setVisible(true);
            }
        });
    }
     public void cargardatos(ListaMedicos listado)
    {
        DefaultTableModel modelo= (DefaultTableModel) Tabla.getModel();
        
        for(Medico Mdc : listado.getLista()){
            {String Especialidad="";
               String PrestadoralIESS="";
                String ListaSeguroMedico="";
                switch (Mdc.getEspecialidad())
                {
         
                    case 0: Especialidad="Angiología.";break;
                    case 1: Especialidad="Dermatología.";break;
                    case 2: Especialidad="Ginecología.";break;
                    case 3: Especialidad="Obstetricia.";break;
                    case 4: Especialidad="Tocología.";break;
                    case 5: Especialidad="Oftalmología.";break;
                    case 6: Especialidad="Otorrinolaringología.";break;
                    case 7: Especialidad="Urología.";break;
                    case 8: Especialidad="Traumatología.";break;
                }
                if(Mdc.getListaSeguroMedico()[0]==1)
                    ListaSeguroMedico=ListaSeguroMedico+"Seguro Mortorio";
                if(Mdc.getListaSeguroMedico()[1]==1)
                    ListaSeguroMedico=ListaSeguroMedico+"; Seguro por 1 o + Hijos";
                if(Mdc.getListaSeguroMedico()[2]==1)
                    ListaSeguroMedico=ListaSeguroMedico+"; Seguro de vida";
                if(Mdc.getListaSeguroMedico()[3]==1)
                    ListaSeguroMedico=ListaSeguroMedico+"; Seguro por discapasidad";
                if(Mdc.getListaSeguroMedico()[4]==1)
                    ListaSeguroMedico=ListaSeguroMedico+"; Seguro Medico Familiar";
                    
                if (Mdc.getPrestadordelIESS().equals("NO"))
                    PrestadoralIESS="NO";
                else
                    PrestadoralIESS="SI";
                Object[] fila={Mdc.getCedula(),Mdc.getNombre(),Mdc.getApellido(),
                    Especialidad,
                    PrestadoralIESS,
                    Mdc.getCodigoRegistroDeColegioDeMedicos(),
                    Mdc.getFechadeRegistro(),
                    ListaSeguroMedico,
                    Mdc.getSueldo()};
                modelo.addRow(fila);
                
            }
        }
        
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
