/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import models.Agenda;
import models.ListaAgenda;

/**
 *
 * @author Steven Pérez
 */
public class frmAgenda extends javax.swing.JFrame {

    ListaAgenda listado = new ListaAgenda();

    /**
     * Creates new form Agenda
     */
    public frmAgenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnactividad = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        chklunes = new javax.swing.JCheckBox();
        chkmartes = new javax.swing.JCheckBox();
        chkmiercoles = new javax.swing.JCheckBox();
        chkjueves = new javax.swing.JCheckBox();
        chkdomingo = new javax.swing.JCheckBox();
        chkviernes = new javax.swing.JCheckBox();
        chksabado = new javax.swing.JCheckBox();
        btnEdit = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rbrealizada = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtactividad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbtactividad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txthinicio = new javax.swing.JTextField();
        rbnorealizada = new javax.swing.JRadioButton();
        txthfinal = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dias de la Actividad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        chklunes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chklunes.setText("Lunes");

        chkmartes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkmartes.setText("Martes");

        chkmiercoles.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkmiercoles.setText("Miercoles");
        chkmiercoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkmiercolesActionPerformed(evt);
            }
        });

        chkjueves.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkjueves.setText("Jueves");

        chkdomingo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkdomingo.setText("Domingo");
        chkdomingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkdomingoActionPerformed(evt);
            }
        });

        chkviernes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chkviernes.setText("Viernes");

        chksabado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chksabado.setText("Sabado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chklunes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkmartes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkmiercoles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkjueves)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkviernes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chksabado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkdomingo))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chklunes)
                    .addComponent(chkmartes)
                    .addComponent(chkmiercoles)
                    .addComponent(chkjueves)
                    .addComponent(chkviernes)
                    .addComponent(chksabado)
                    .addComponent(chkdomingo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnRemove.setText("Eliminar");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("AGENDAR ACTIVIDADES");

        btnactividad.add(rbrealizada);
        rbrealizada.setSelected(true);
        rbrealizada.setText("Realizada");

        jLabel1.setText("Actividad");

        txtactividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtactividadActionPerformed(evt);
            }
        });
        txtactividad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtactividadKeyTyped(evt);
            }
        });

        jLabel2.setText("Tipo de Actividad");

        cbtactividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Academica", "Deportiva", "Artistica", "Recreativa" }));

        jLabel3.setText("Hora de Inicio");

        jLabel5.setText("Hora Final");

        txthinicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthinicioKeyTyped(evt);
            }
        });

        btnactividad.add(rbnorealizada);
        rbnorealizada.setText("No Realizada");
        rbnorealizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnorealizadaActionPerformed(evt);
            }
        });

        txthfinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthfinalKeyTyped(evt);
            }
        });

        btnAdd.setText("Agregar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtactividad, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbtactividad, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txthinicio)
                                            .addComponent(txthfinal))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(rbrealizada)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rbnorealizada))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnAdd)
                        .addGap(25, 25, 25)
                        .addComponent(btnEdit)
                        .addGap(29, 29, 29)
                        .addComponent(btnRemove)
                        .addGap(32, 32, 32)
                        .addComponent(btnListar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtactividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbrealizada)
                    .addComponent(rbnorealizada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbtactividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txthinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txthfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnRemove)
                    .addComponent(btnListar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkmiercolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkmiercolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkmiercolesActionPerformed

    private void chkdomingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkdomingoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkdomingoActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String nombre = txtactividad.getText();
        String hinicio = txthinicio.getText();
        String hfinal = txthfinal.getText();
        String actividad;
        if (rbrealizada.isSelected()) {
            actividad = "Realizada";
        } else {
            actividad = "No Realizada";
        }
        int t_ac = cbtactividad.getSelectedIndex();
        int[] dia_actividad = new int[7];
        if (chklunes.isSelected()) {
            dia_actividad[0] = 1;
        } else {
            dia_actividad[0] = 0;
        }
        if (chkmartes.isSelected()) {
            dia_actividad[1] = 1;
        } else {
            dia_actividad[1] = 0;
        }
        if (chkmiercoles.isSelected()) {
            dia_actividad[2] = 1;
        } else {
            dia_actividad[2] = 0;
        }
        if (chkjueves.isSelected()) {
            dia_actividad[3] = 1;
        } else {
            dia_actividad[3] = 0;
        }
        if (chkviernes.isSelected()) {
            dia_actividad[4] = 1;
        } else {
            dia_actividad[4] = 0;
        }
        if (chksabado.isSelected()) {
            dia_actividad[5] = 1;
        } else {
            dia_actividad[5] = 0;
        }
        if (chkdomingo.isSelected()) {
            dia_actividad[6] = 1;
        } else {
            dia_actividad[6] = 0;
        }
        Agenda p = new Agenda(nombre, t_ac, hinicio, hfinal, actividad, dia_actividad);
        this.listado.Actualizarxnombre(p);
        limpiar();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        String nombre = JOptionPane.showInputDialog("Ingrese el nombre de la actividad");
        int confirm = JOptionPane.showConfirmDialog(this, "Seguro que quiere eliminar esta actividad");
        if (confirm == 0) {
            this.listado.Eliminarxnombre(nombre);
        }
        limpiar();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        ListarAgenda listar = new ListarAgenda();
        listar.cargardatos(this.listado);
        listar.setVisible(true);
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        Agenda p;
        String nombre = JOptionPane.showInputDialog("Ingrese el nombre de la actividad");
        try {
            p = this.listado.Buscarxnombre(nombre);
            txtactividad.setText(p.getNombre());
            txthinicio.setText(p.getH_inicio());
            txthfinal.setText(p.getH_final());
            if (p.getActividad().equals("Realizada")) {
                rbrealizada.setSelected(true);
            } else {
                rbnorealizada.setSelected(true);
            }
            cbtactividad.setSelectedIndex(p.getT_ac());
            if (p.getDia_actividad()[0] == 1) {
                chklunes.setSelected(true);
            } else {
                chklunes.setSelected(false);
            }
            if (p.getDia_actividad()[1] == 1) {
                chkmartes.setSelected(true);
            } else {
                chkmartes.setSelected(false);
            }
            if (p.getDia_actividad()[2] == 1) {
                chkmiercoles.setSelected(true);
            } else {
                chkmiercoles.setSelected(false);
            }
            if (p.getDia_actividad()[3] == 1) {
                chkjueves.setSelected(true);
            } else {
                chkjueves.setSelected(false);
            }
            if (p.getDia_actividad()[4] == 1) {
                chkviernes.setSelected(true);
            } else {
                chkviernes.setSelected(false);
            }
            if (p.getDia_actividad()[5] == 1) {
                chksabado.setSelected(true);
            } else {
                chksabado.setSelected(false);
            }
            if (p.getDia_actividad()[6] == 1) {
                chkdomingo.setSelected(true);
            } else {
                chkdomingo.setSelected(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Registro no encontrado...");
            limpiar();
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtactividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtactividadActionPerformed

    }//GEN-LAST:event_txtactividadActionPerformed

    private void txtactividadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtactividadKeyTyped
        char validar = evt.getKeyChar();
        int c = evt.getKeyChar();
        if (Character.isDigit(validar) && (!((c > 65 && c <= 98) || (c >= 97 && c <= 22)))) {
            getToolkit().beep();
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo Letras");
        }
        System.out.println(c);
    }//GEN-LAST:event_txtactividadKeyTyped

    private void txthinicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthinicioKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_txthinicioKeyTyped

    private void rbnorealizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnorealizadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnorealizadaActionPerformed

    private void txthfinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthfinalKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }
    }//GEN-LAST:event_txthfinalKeyTyped

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String nombre = txtactividad.getText();
        String hinicio = txthinicio.getText();
        String hfinal = txthfinal.getText();
        String actividad;
        if (rbrealizada.isSelected()) {
            actividad = "Realizada";
        } else {
            actividad = "No Realizada";
        }
        int t_ac = cbtactividad.getSelectedIndex();
        int[] dia_actividad = new int[7];
        if (chklunes.isSelected()) {
            dia_actividad[0] = 1;
        } else {
            dia_actividad[0] = 0;
        }
        if (chkmartes.isSelected()) {
            dia_actividad[1] = 1;
        } else {
            dia_actividad[1] = 0;
        }
        if (chkmiercoles.isSelected()) {
            dia_actividad[2] = 1;
        } else {
            dia_actividad[2] = 0;
        }
        if (chkjueves.isSelected()) {
            dia_actividad[3] = 1;
        } else {
            dia_actividad[3] = 0;
        }
        if (chkviernes.isSelected()) {
            dia_actividad[4] = 1;
        } else {
            dia_actividad[4] = 0;
        }
        if (chksabado.isSelected()) {
            dia_actividad[5] = 1;
        } else {
            dia_actividad[5] = 0;
        }
        if (chkdomingo.isSelected()) {
            dia_actividad[6] = 1;
        } else {
            dia_actividad[6] = 0;
        }
        Agenda p = new Agenda(nombre, t_ac, hinicio, hfinal, actividad, dia_actividad);
        this.listado.Agregar(p);
        limpiar();
    }//GEN-LAST:event_btnAddActionPerformed
    private void limpiar() {
        txtactividad.setText("");
        txthinicio.setText("");
        txthfinal.setText("");
        cbtactividad.setSelectedIndex(0);
        chklunes.setSelected(false);
        chkmartes.setSelected(false);
        chkmiercoles.setSelected(false);
        chkjueves.setSelected(false);
        chkviernes.setSelected(false);
        chksabado.setSelected(false);
        chkdomingo.setSelected(false);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnRemove;
    private javax.swing.ButtonGroup btnactividad;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JComboBox<String> cbtactividad;
    private javax.swing.JCheckBox chkdomingo;
    private javax.swing.JCheckBox chkjueves;
    private javax.swing.JCheckBox chklunes;
    private javax.swing.JCheckBox chkmartes;
    private javax.swing.JCheckBox chkmiercoles;
    private javax.swing.JCheckBox chksabado;
    private javax.swing.JCheckBox chkviernes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbnorealizada;
    private javax.swing.JRadioButton rbrealizada;
    private javax.swing.JTextField txtactividad;
    private javax.swing.JTextField txthfinal;
    private javax.swing.JTextField txthinicio;
    // End of variables declaration//GEN-END:variables
}
