package Views;

import main.ListaMedicos;
import main.Medico;
import Views.MostrarDatosMedicos;
import java.awt.Color;
import javax.swing.JOptionPane;

public class JFrame_Medico extends javax.swing.JFrame {
    ListaMedicos listado = new ListaMedicos();
    
    
    public JFrame_Medico() {
        initComponents();
        this.getContentPane().setBackground(Color.lightGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdbGruo_PrestadorIESS = new javax.swing.ButtonGroup();
        btn_Agregar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_Buscar = new javax.swing.JButton();
        btn_listar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        cmb_especialidad = new javax.swing.JComboBox<>();
        txt_sueldo = new javax.swing.JTextField();
        rdb_SI = new javax.swing.JRadioButton();
        rdb_NO = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        chec_Mortorio = new javax.swing.JCheckBox();
        chec_Seguropor1omashijos = new javax.swing.JCheckBox();
        chec_segurodevida = new javax.swing.JCheckBox();
        chec_seguroMedicoFamiliar = new javax.swing.JCheckBox();
        chec_seguropordiscapasidad = new javax.swing.JCheckBox();
        txt_cdR_del_coleMedicos = new javax.swing.JTextField();
        txt_FechadeRegistro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Médico");

        btn_Agregar.setText("Agregar");
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });

        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        btn_Buscar.setText("Buscar");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        btn_listar.setText("Listar");
        btn_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jLabel1.setText("Cedula:");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jLabel3.setText("Apellido:");

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jLabel4.setText("Especialidad:");

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jLabel5.setText("Prestador del IESS:");

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jLabel6.setText("Codigo de Registro del colegio de Medicos:");

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jLabel7.setText("Fecha de Registro:");

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Book", 1, 18)); // NOI18N
        jLabel9.setText("Sueldo:");

        txt_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cedulaKeyTyped(evt);
            }
        });

        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });

        txt_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidoKeyTyped(evt);
            }
        });

        cmb_especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  --Selecione Especialidad-- ", "     Angiología.", "    Dermatología.", "    Ginecología. ", "    Obstetricia. ", "    Tocología.", "    Oftalmología.", "    Otorrinolaringología.", "    Urología.", "    Traumatología." }));

        txt_sueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_sueldoKeyTyped(evt);
            }
        });

        rdbGruo_PrestadorIESS.add(rdb_SI);
        rdb_SI.setText("Si");

        rdbGruo_PrestadorIESS.add(rdb_NO);
        rdb_NO.setText("NO");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Lista de seguros medicos asociados:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Felix Titling", 0, 14))); // NOI18N

        chec_Mortorio.setText("Seguro Mortorio");

        chec_Seguropor1omashijos.setText("Seguro por 1 o + hijos");

        chec_segurodevida.setText("Seguro de vida");

        chec_seguroMedicoFamiliar.setText("seguro Medico Familiar");

        chec_seguropordiscapasidad.setText("seguro por discapasidad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chec_Mortorio)
                    .addComponent(chec_Seguropor1omashijos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chec_segurodevida))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chec_seguropordiscapasidad)
                    .addComponent(chec_seguroMedicoFamiliar))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chec_Mortorio)
                    .addComponent(chec_seguropordiscapasidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chec_Seguropor1omashijos)
                    .addComponent(chec_seguroMedicoFamiliar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chec_segurodevida)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Footlight MT Light", 2, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Registro de Médico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txt_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txt_FechadeRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_cedula)
                                    .addComponent(txt_nombre)
                                    .addComponent(txt_apellido)
                                    .addComponent(cmb_especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rdb_SI)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rdb_NO)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_listar)
                                .addComponent(btn_Buscar)
                                .addComponent(btn_Eliminar)
                                .addComponent(btn_Agregar)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(txt_cdR_del_coleMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmb_especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rdb_SI)
                            .addComponent(rdb_NO)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btn_Agregar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Buscar)
                        .addGap(37, 37, 37)
                        .addComponent(btn_listar)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_cdR_del_coleMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_FechadeRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cedulaKeyTyped
            char cedula = evt.getKeyChar();
            if ((Character.isLetter(cedula))) {
                evt.consume();
                JOptionPane.showMessageDialog(null, "Ingrese solo Numeros");
            }    
    }//GEN-LAST:event_txt_cedulaKeyTyped

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        char validar = evt.getKeyChar();
        int c = evt.getKeyChar();
        if (Character.isDigit(validar) && (!((c > 65 && c <= 98) || (c >= 97 && c <= 22)))) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo Letras");
        }
        System.out.println(c);
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoKeyTyped
        char validar = evt.getKeyChar();
        int c = evt.getKeyChar();
        if (Character.isDigit(validar) && (!((c > 65 && c <= 98) || (c >= 97 && c <= 22)))) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo Letras");
        }
        System.out.println(c);
    }//GEN-LAST:event_txt_apellidoKeyTyped

    private void txt_sueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sueldoKeyTyped
        char sueldo = evt.getKeyChar();
        if ((Character.isLetter(sueldo))) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Ingrese solo Numeros");
        }
    }//GEN-LAST:event_txt_sueldoKeyTyped

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        if (!validarVacios()) {
            String Cedula = txt_cedula.getText();
            String Nombre = txt_nombre.getText();
            String Apellido = txt_apellido.getText();
            int Especialidades = cmb_especialidad.getSelectedIndex();
            if (Especialidades == 0) {
                JOptionPane.showMessageDialog(null, "--Seleccione Vendedor--");
            }
            String Prestador =" ";
            if (rdb_SI.isSelected()) {
                Prestador = "Si";
            } else if (rdb_NO.isSelected()) {
                Prestador = "NO";
            }
            String cdMedico = txt_cdR_del_coleMedicos.getText();
            String FechadeRegistro = txt_FechadeRegistro.getText();

            int[] ListaMedicos=new int[5];
            if  (chec_Mortorio.isSelected()) {ListaMedicos [0] = 1;}
            else  {ListaMedicos [0] = 0;}
            if  (chec_Seguropor1omashijos.isSelected())   {ListaMedicos [1] = 1;}
            else { ListaMedicos [1] = 0;}
            if  (chec_segurodevida.isSelected()) {ListaMedicos [2] = 1;}
            else {ListaMedicos [2] = 0;}
            if  (chec_seguropordiscapasidad.isSelected())   {ListaMedicos [3] = 1;}
            else {ListaMedicos [3] = 0;}
            if  (chec_seguroMedicoFamiliar.isSelected()) {ListaMedicos [4] = 1;}
            else  {ListaMedicos [4] = 0;}

            int Sueldo = Integer.valueOf(txt_sueldo.getText());

            Medico Mdc = new Medico(Nombre, Apellido, Cedula, Sueldo, cdMedico, FechadeRegistro, Prestador, Especialidades, ListaMedicos);
            this.listado.Agregar(Mdc);
        } else {
            JOptionPane.showMessageDialog(null, "\t " + "         " + " \t\t Datos \n\t --INCOMPLETOS-- ");
        }

    }//GEN-LAST:event_btn_AgregarActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        // TODO add your handling code here:
        String cedula = JOptionPane.showInputDialog("Ingrese la cedula de la persona a eliminar");
        int confirm = JOptionPane.showConfirmDialog(this,"Seguro que desea eliminar la Cedula: "+cedula);
        if (confirm == 0) {
            this.listado.Eliminar_cedula(cedula);
        }

    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        // TODO add your handling code here:
        Medico Mdc;
        String Cedula = JOptionPane.showInputDialog("Ingrese la cedula");
        try {

            Mdc = this.listado.Buscar_cedula(Cedula);
            txt_cedula.setText(Mdc.getCedula());
            txt_nombre.setText(Mdc.getNombre());
            txt_apellido.setText(Mdc.getApellido());
            cmb_especialidad.setSelectedItem(Mdc.getEspecialidad());
            if (Mdc.getPrestadordelIESS().equals("SI")) {
                rdb_SI.setSelected(true);
            } else if (Mdc.getPrestadordelIESS().equals("NO")) {
                rdb_NO.setSelected(true);
            }
            txt_cdR_del_coleMedicos.setText(Mdc.getCodigoRegistroDeColegioDeMedicos());
            txt_FechadeRegistro.setText(Mdc.getFechadeRegistro());

            if (chec_Mortorio.isSelected()) {
                chec_Mortorio.setSelected(true);
            } else {
                chec_Mortorio.setSelected(false);
            }
            if (chec_Seguropor1omashijos.isSelected()) {
                chec_Seguropor1omashijos.setSelected(true);
            } else {
                chec_Seguropor1omashijos.setSelected(false);
            }
            if (chec_segurodevida.isSelected()) {
                chec_segurodevida.setSelected(true);
            } else {
                chec_segurodevida.setSelected(false);
            }
            if (chec_seguropordiscapasidad.isSelected()) {
                chec_seguropordiscapasidad.setSelected(true);
            } else {
                chec_seguropordiscapasidad.setSelected(false);
            }
            if (chec_seguroMedicoFamiliar.isSelected()) {
                chec_seguroMedicoFamiliar.setSelected(true);
            } else {
                chec_seguroMedicoFamiliar.setSelected(false);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro no encontrado. . .");
        }

    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void btn_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarActionPerformed
        // TODO add your handling code here:
        MostrarDatosMedicos listar = new MostrarDatosMedicos();
        listar.cargardatos(this.listado);
        listar.setVisible(true);
    }//GEN-LAST:event_btn_listarActionPerformed
     private boolean validarVacios() {
        boolean vacio = false;
        if (txt_cedula.getText().isEmpty()) {
            vacio = true;
        } else if (txt_nombre.getText().isEmpty() ){
            vacio = true;
        } else if (txt_apellido.getText().isEmpty() ){
            vacio = true;
        } else if (cmb_especialidad.getSelectedItem().equals(0)){
            vacio = true;
        }else if (!rdb_SI.isSelected() && !rdb_NO.isSelected() ) {
            vacio = true;
        }else if (txt_cdR_del_coleMedicos.getText().isEmpty()) {
            vacio = true;
        }else if (txt_sueldo.getText().isEmpty()) {
            vacio =true;
        }else if (txt_FechadeRegistro.getText().isEmpty()) {
            vacio =true;
        }
   
        return vacio;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Medico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_listar;
    private javax.swing.JCheckBox chec_Mortorio;
    private javax.swing.JCheckBox chec_Seguropor1omashijos;
    private javax.swing.JCheckBox chec_seguroMedicoFamiliar;
    private javax.swing.JCheckBox chec_segurodevida;
    private javax.swing.JCheckBox chec_seguropordiscapasidad;
    private javax.swing.JComboBox<String> cmb_especialidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup rdbGruo_PrestadorIESS;
    private javax.swing.JRadioButton rdb_NO;
    private javax.swing.JRadioButton rdb_SI;
    private javax.swing.JTextField txt_FechadeRegistro;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_cdR_del_coleMedicos;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_sueldo;
    // End of variables declaration//GEN-END:variables
}
