/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import models.Datos;
import models.listaJuegos;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class listarDatosJuegos extends javax.swing.JFrame {

    /**
     * Creates new form listarDatosJuegos
     */
    public listarDatosJuegos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbdatos = new javax.swing.JTable();
        btcerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Fecha de Lanzamiento", "Precio", "Tipo de consola", "Apto para niños", "Genero"
            }
        ));
        jScrollPane1.setViewportView(tbdatos);

        btcerrar.setText("CERRAR");
        btcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btcerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btcerrar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btcerrarActionPerformed

    public void cargardatos(listaJuegos listado) {
        DefaultTableModel modelo = (DefaultTableModel) tbdatos.getModel();

        for (Datos p : listado.getLista()) {
            String consola = "";
            String apto = "";
            String genero = "";

            switch (p.getConsola()) {
                case 0:
                    consola = "";
                    break;
                case 1:
                    consola = "Ps3";
                    break;
                case 2:
                    consola = "Ps4";
                    break;
                case 3:
                    consola = "Xbox One";
                    break;
                case 4:
                    consola = "Pc";
                    break;
                case 5:
                    consola = "Otro";
                    break;
            }

            if (p.getGenero()[0] == 1) {
                genero = " Accion";
            }
            if (p.getGenero()[1] == 1) {
                genero = genero + "; Aventura";
            }
            if (p.getGenero()[2] == 1) {
                genero = genero + "; Shooters";
            }
            if (p.getGenero()[3] == 1) {
                genero = genero + "; Carreras";
            }
            if (p.getGenero()[4] == 1) {
                genero = genero + "; Educativo";
            }
            if (p.getGenero()[5] == 1) {
                genero = genero + "; Estrategia";
            }

            if (p.getApto().equals("SI")) {
                apto = "SI";
            } else {
                apto = "NO";
            }
            Object[] fila = {p.getNombre(),
                p.getFechaLan(),
                p.getPrecio(),
                consola, apto, genero};
            modelo.addRow(fila);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcerrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbdatos;
    // End of variables declaration//GEN-END:variables
}
