/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.table.DefaultTableModel;
import models.Agenda;
import models.ListaAgenda;

/**
 *
 * @author Steven Pérez
 */
public class ListarAgenda extends javax.swing.JFrame {

    /**
     * Creates new form ListarAgenda
     */
    public ListarAgenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbdatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Actividad", "Tipo de Actividad", "Hora de Inicio", "Hora Final", "Accion", "Dias de la Actividad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbdatos);

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 611, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 433, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(50, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void cargardatos(ListaAgenda listado) {
        DefaultTableModel modelo = (DefaultTableModel) tbdatos.getModel();

        for (Agenda p : listado.getLista()) {
            String tac = "";
            String dia_actividad = "";
            String actividad = "";
            switch (p.getT_ac()) {
                case 0:
                    tac = "Academica";
                    break;
                case 1:
                    tac = "Deportiva";
                    break;
                case 2:
                    tac = "Artistica";
                    break;
                case 3:
                    tac = "Recreativa";
                    break; //Academica-Deportiva-Artistica-Recreativa
            }
            if (p.getDia_actividad()[0] == 1) {
                dia_actividad = "Lunes";
            }
            if (p.getDia_actividad()[1] == 1) {
                dia_actividad = dia_actividad + "; Martes";
            }
            if (p.getDia_actividad()[2] == 1) {
                dia_actividad = dia_actividad + "; Miercoles";
            }
            if (p.getDia_actividad()[3] == 1) {
                dia_actividad = dia_actividad + "; Jueves";
            }
            if (p.getDia_actividad()[4] == 1) {
                dia_actividad = dia_actividad + "; Viernes";
            }
            if (p.getDia_actividad()[5] == 1) {
                dia_actividad = dia_actividad + "; Sabado";
            }
            if (p.getDia_actividad()[6] == 1) {
                dia_actividad = dia_actividad + "; Domingo";
            }
            if (p.getActividad().equals("Realizada")) {
                actividad = "Realizada";
            } else {
                actividad = "No Realizada";
            }
            Object[] fila = {p.getNombre(), tac, p.getH_inicio(), p.getH_final(), actividad, dia_actividad};
            modelo.addRow(fila);

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbdatos;
    // End of variables declaration//GEN-END:variables
}
