/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import models.Profesor;
import models.listaprofesor;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class listadoDocente extends javax.swing.JFrame {

    /**
     * Creates new form listado
     */
    public listadoDocente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbdatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Cédula", "Título", "Sueldo", "Asociado a Colegio", "Profesionales asociados"
            }
        ));
        jScrollPane1.setViewportView(tbdatos);

        jButton1.setText("CERRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void cargardatos(listaprofesor listado) {
        DefaultTableModel modelo = (DefaultTableModel) tbdatos.getModel();

        for (Profesor p : listado.getLista()) {
            String titulo = "";
            String profesionales = "";
            String asociado = "";
            switch (p.getTitulo()) {
                case 0:
                    titulo = "Ninguna";
                    break;
                case 1:
                    titulo = "Licenciado";
                    break;
                case 2:
                    titulo = "Ingeniero";
                    break;

            }
            if (p.getProfesionales()[0] == 1) {
                profesionales = " Estudiante";
            }
            if (p.getProfesionales()[1] == 1) {
                profesionales = profesionales + "; Catedrático de Universidad";
            }
            if (p.getProfesionales()[2] == 1) {
                profesionales = profesionales + "; Docente";
            }
            if (p.getProfesionales()[3] == 1) {
                profesionales = profesionales + "; Docente-Investigación";
            }
            if (p.getProfesionales()[4] == 1) {
                profesionales = profesionales + "; Médico";
            }

            if (p.getAsociado().equals("SI")) {
                asociado = "SI";
            } else {
                asociado = "NO";
            }
            Object[] fila = {p.getNombre(),
                p.getApellido(),
                p.getCedula(), titulo,
                p.getSueldo(), asociado, profesionales};
            modelo.addRow(fila);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbdatos;
    // End of variables declaration//GEN-END:variables

}
