/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import main.Datos;
import main.listaJuegos;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class registroDeJuegos extends javax.swing.JFrame {

    /**
     * Creates new form registroDeJuegos
     */
    listaJuegos obj= new listaJuegos();
    public registroDeJuegos() {
        initComponents();
        this.getContentPane().setBackground(Color.GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgapto = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        cbtipo = new javax.swing.JComboBox<>();
        rdbSi = new javax.swing.JRadioButton();
        rdbNO = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        chkaccion = new javax.swing.JCheckBox();
        chkaventura = new javax.swing.JCheckBox();
        chkshooter = new javax.swing.JCheckBox();
        chkeducativo = new javax.swing.JCheckBox();
        chkcarreras = new javax.swing.JCheckBox();
        chkestrategia = new javax.swing.JCheckBox();
        btlistar = new javax.swing.JToggleButton();
        btagregar = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        btbuscar = new javax.swing.JButton();
        btcerrar = new javax.swing.JButton();
        btlimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaComentarios = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setText("Registro de juegos");

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel2.setText("Nombre del juego: ");

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel3.setText("Fecha de lanzamiento:");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel4.setText("Precio:");

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel5.setText("Tipo de Consola:");

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel6.setText("Apto para niños:");

        txtprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecioKeyTyped(evt);
            }
        });

        cbtipo.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        cbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Escoja el tipo de consola ---", "Ps3", "Ps4", "Xbox one", "Pc", "otro." }));

        btgapto.add(rdbSi);
        rdbSi.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        rdbSi.setText("SI");

        btgapto.add(rdbNO);
        rdbNO.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        rdbNO.setText("NO");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Genero"));

        chkaccion.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        chkaccion.setText("Accion");
        chkaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkaccionActionPerformed(evt);
            }
        });

        chkaventura.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        chkaventura.setText("Aventura");

        chkshooter.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        chkshooter.setText("Shooter");

        chkeducativo.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        chkeducativo.setText("Educativo");

        chkcarreras.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        chkcarreras.setText("Carreras");

        chkestrategia.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        chkestrategia.setText("Estrategia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkaccion)
                    .addComponent(chkaventura)
                    .addComponent(chkshooter))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkestrategia)
                    .addComponent(chkcarreras)
                    .addComponent(chkeducativo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(chkestrategia))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkaccion)
                            .addComponent(chkcarreras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkaventura)
                            .addComponent(chkeducativo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkshooter)))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        btlistar.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btlistar.setText("LISTAR");
        btlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlistarActionPerformed(evt);
            }
        });

        btagregar.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btagregar.setText("AGREGAR");
        btagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btagregarActionPerformed(evt);
            }
        });

        bteliminar.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        bteliminar.setText("ELIMINAR");
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });

        btbuscar.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btbuscar.setText("BUSCAR");
        btbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuscarActionPerformed(evt);
            }
        });

        btcerrar.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btcerrar.setText("CERRAR");
        btcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcerrarActionPerformed(evt);
            }
        });

        btlimpiar.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        btlimpiar.setText("LIMPIAR");
        btlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlimpiarActionPerformed(evt);
            }
        });

        txtaComentarios.setColumns(20);
        txtaComentarios.setRows(5);
        jScrollPane1.setViewportView(txtaComentarios);

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel7.setText("Comentario del juego:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btagregar)
                        .addGap(18, 18, 18)
                        .addComponent(bteliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btbuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btlistar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rdbSi)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rdbNO))
                                        .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtfecha)
                                            .addGap(24, 24, 24))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btlimpiar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btcerrar))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btcerrar)
                            .addComponent(btlimpiar))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rdbSi)
                                        .addComponent(rdbNO))))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btagregar)
                    .addComponent(bteliminar)
                    .addComponent(btbuscar)
                    .addComponent(btlistar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkaccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkaccionActionPerformed

    private void btlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlistarActionPerformed
        // TODO add your handling code here:
        listarDatosJuegos listar = new listarDatosJuegos();
        listar.cargardatos(this.obj);
        listar.setVisible(true);
        
    }//GEN-LAST:event_btlistarActionPerformed

    private void btagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btagregarActionPerformed
        // TODO add your handling code here:
        if (!validaVacios()) {
            String nombre = txtnombre.getText();
            String fechalan = txtfecha.getText();
            String precio = txtprecio.getText();
            String Apto;
            int tipo = cbtipo.getSelectedIndex();
            int[] genero = new int[6];
            String comentarios= txtaComentarios.getText();
            //Apto
            if (rdbSi.isSelected()) {
                Apto = "SI";
            } else {
                Apto = "NO";
            }
            //Genero
            if (chkaccion.isSelected()) {
                genero[0] = 1;
            } else {
                genero[0] = 0;
            }
            if (chkaventura.isSelected()) {
                genero[1] = 1;
            } else {
                genero[1] = 0;
            }
            if (chkshooter.isSelected()) {
                genero[2] = 1;
            } else {
                genero[2] = 0;
            }
            if (chkcarreras.isSelected()) {
                genero[3] = 1;
            } else {
                genero[3] = 0;
            }
            if (chkeducativo.isSelected()) {
                genero[4] = 1;
            } else {
                genero[4] = 0;
            }
            if (chkestrategia.isSelected()) {
                genero[5] = 1;
            } else {
                genero[5] = 0;
            }
            Datos p = new Datos(nombre, fechalan, precio, tipo,Apto, genero, comentarios);
            this.obj.Agregar(p);
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "Datos incompletos");
        }
    }//GEN-LAST:event_btagregarActionPerformed
private void limpiar() {
        txtnombre.setText(" ");
        txtfecha.setText(" ");
        txtprecio.setText(" ");
        txtaComentarios.setText("");
        btgapto.clearSelection();
        cbtipo.setSelectedIndex(0);
        chkaccion.setSelected(false);
        chkaventura.setSelected(false);
        chkshooter.setSelected(false);
        chkeducativo.setSelected(false);
        chkcarreras.setSelected(false);
        chkestrategia.setSelected(false);
    }
    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog("Ingrese el Numero del juego a eliminar: ");
        String fecha = JOptionPane.showInputDialog("Ingrese la Fecha de lanzamiento: ");
        int confirm = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar el registro: ");
        if (confirm == 0) {
            this.obj.EliminarxFecha(nombre, fecha);
        }
    }//GEN-LAST:event_bteliminarActionPerformed
private boolean validaVacios() {
        boolean vacio = false;
        if (txtnombre.getText().isEmpty()) {
            vacio = true;
        } else if (txtfecha.getText().isEmpty()) {
            vacio = true;
        } else if (cbtipo.getSelectedIndex() == 0) {
            vacio = true;
        } else if (txtprecio.getText().isEmpty()) {
            vacio = true;
        }else if (btgapto.equals(0)) {
            vacio = true;
        }
        return vacio;
    }
    private void btbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuscarActionPerformed
        // TODO add your handling code here:
        Datos p;
        String nombre = JOptionPane.showInputDialog("Ingrese el nombre: ");
        String fecha = JOptionPane.showInputDialog("Ingrese La Fecha de lanzamiento: ");
        try{
            p = this.obj.BuscarxFecha(nombre, fecha);
            txtnombre.setText(p.getNombre());
            txtfecha.setText(p.getFechaLan());
            txtprecio.setText(p.getPrecio());
            txtaComentarios.setText(p.getComentarios());
            if (p.getApto().equals("SI")) {
                rdbSi.setSelected(true);
            } else {
                rdbNO.setSelected(true);
            }
            cbtipo.setSelectedIndex(p.getConsola());
            //check
            if (p.getGenero()[0] == 1) {
                chkaccion.setSelected(true);
            } else {
                chkaccion.setSelected(false);
            }
            if (p.getGenero()[1] == 1) {
                chkaventura.setSelected(true);
            } else {
                chkaventura.setSelected(false);
            }
            if (p.getGenero()[2] == 1) {
                chkshooter.setSelected(true);
            } else {
                chkshooter.setSelected(false);
            }
            if (p.getGenero()[3] == 1) {
                chkcarreras.setSelected(true);
            } else {
                chkcarreras.setSelected(false);
            }
            if (p.getGenero()[4] == 1) {
                chkeducativo.setSelected(true);
            } else {
                chkeducativo.setSelected(false);
            }
            if (p.getGenero()[5] == 1) {
                chkestrategia.setSelected(true);
            } else {
                chkestrategia.setSelected(false);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Ingrese bien los Datos.");
        }
    }//GEN-LAST:event_btbuscarActionPerformed

    private void btcerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btcerrarActionPerformed

    private void btlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btlimpiarActionPerformed

    private void txtprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }       
    }//GEN-LAST:event_txtprecioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registroDeJuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registroDeJuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registroDeJuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registroDeJuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registroDeJuegos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btagregar;
    private javax.swing.JButton btbuscar;
    private javax.swing.JButton btcerrar;
    private javax.swing.JButton bteliminar;
    private javax.swing.ButtonGroup btgapto;
    private javax.swing.JButton btlimpiar;
    private javax.swing.JToggleButton btlistar;
    private javax.swing.JComboBox<String> cbtipo;
    private javax.swing.JCheckBox chkaccion;
    private javax.swing.JCheckBox chkaventura;
    private javax.swing.JCheckBox chkcarreras;
    private javax.swing.JCheckBox chkeducativo;
    private javax.swing.JCheckBox chkestrategia;
    private javax.swing.JCheckBox chkshooter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbNO;
    private javax.swing.JRadioButton rdbSi;
    private javax.swing.JTextArea txtaComentarios;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
