/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import main.Profesor;
import main.listaprofesor;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */

public class RegistroDocente extends javax.swing.JFrame {

    listaprofesor lista = new listaprofesor();
    
    public RegistroDocente() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbcolegio = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtsueldo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        si = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        chkest = new javax.swing.JCheckBox();
        chkcatU = new javax.swing.JCheckBox();
        chkdoc = new javax.swing.JCheckBox();
        chkdocI = new javax.swing.JCheckBox();
        chkmed = new javax.swing.JCheckBox();
        cbtitulo = new javax.swing.JComboBox<>();
        tbAgergar = new javax.swing.JButton();
        tbEliminar = new javax.swing.JButton();
        tbBuscar = new javax.swing.JButton();
        tbistar = new javax.swing.JButton();
        tbCerrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("REGISTRO DOCENTE");

        jLabel2.setText("NOMBRE:");

        jLabel3.setText("APELLIDO:");

        jLabel4.setText("CÉDULA:");

        jLabel5.setText("TITULO:");

        jLabel6.setText("SUELDO:");

        jLabel7.setText("ASOCIADO A COLEGIO RPOFESIONAL:");

        tbcolegio.add(si);
        si.setText("SI");

        tbcolegio.add(no);
        no.setText("NO");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("PROFESIONALES ASOCIADO")));

        chkest.setText("Estudiante");

        chkcatU.setText("Catedrático de Universidad");

        chkdoc.setText("Docente");

        chkdocI.setText("Docente-Invetigadora");

        chkmed.setText("Médico");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkest)
                    .addComponent(chkcatU))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkdocI)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkdoc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(chkmed)
                        .addGap(46, 46, 46))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkest)
                    .addComponent(chkdoc)
                    .addComponent(chkmed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkcatU)
                    .addComponent(chkdocI))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        cbtitulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Licenciado", "Ingeniero" }));

        tbAgergar.setText("AGREGAR");
        tbAgergar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbAgergarActionPerformed(evt);
            }
        });

        tbEliminar.setText("ELIMINAR");
        tbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbEliminarActionPerformed(evt);
            }
        });

        tbBuscar.setText("BUSCAR");
        tbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBuscarActionPerformed(evt);
            }
        });

        tbistar.setText("LISTAR");
        tbistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbistarActionPerformed(evt);
            }
        });

        tbCerrar.setText("CERRAR");
        tbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCerrarActionPerformed(evt);
            }
        });

        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(26, 26, 26)
                                        .addComponent(si)
                                        .addGap(18, 18, 18)
                                        .addComponent(no))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                                    .addComponent(txtapellido))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(74, 74, 74)
                                                        .addComponent(jLabel4)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(72, 72, 72)
                                                        .addComponent(jLabel6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(cbtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(217, 217, 217))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(jButton2)
                                .addGap(54, 54, 54)
                                .addComponent(tbCerrar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(tbAgergar)
                .addGap(89, 89, 89)
                .addComponent(tbEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbBuscar)
                .addGap(105, 105, 105)
                .addComponent(tbistar)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtsueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(si)
                    .addComponent(no))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbAgergar)
                    .addComponent(tbEliminar)
                    .addComponent(tbBuscar)
                    .addComponent(tbistar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbCerrar)
                    .addComponent(jButton2))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    private void tbistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbistarActionPerformed
        listadoDocente listar= new listadoDocente();
        listar.cargardatos(this.lista);
        listar.setVisible(true);    
    }//GEN-LAST:event_tbistarActionPerformed

    private void tbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCerrarActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_tbCerrarActionPerformed

    private void tbAgergarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbAgergarActionPerformed
        String nombre = txtnombre.getText();
        String apellido = txtapellido.getText();
        String cedula = txtcedula.getText();
        String sueldo=txtsueldo.getText();
        String asociado;
        int titulo = cbtitulo.getSelectedIndex();
        int[] profesionales = new int[5];
        
        if (si.isSelected()) {
            asociado = "SI";
        } else {
            asociado = "NO";
        }
        
        if (chkest.isSelected()) {
            profesionales[0] = 1;
        } else {
            profesionales[0] = 0;
        }
        if (chkcatU.isSelected()) {
            profesionales[1] = 1;
        } else {
            profesionales[1] = 0;
        }
        if (chkdoc.isSelected()) {
            profesionales[2] = 1;
        } else {
            profesionales[2] = 0;
        }
        if (chkdocI.isSelected()) {
            profesionales[3] = 1;
        } else {
            profesionales[3] = 0;
        }
        if (chkmed.isSelected()) {
            profesionales[4] = 1;
        } else {
            profesionales[4] = 0;
        
        }
        Profesor p = new Profesor(nombre, apellido, cedula, titulo, sueldo, asociado, profesionales);
        this.lista.Agregar(p);
        limpiar();
    
    }//GEN-LAST:event_tbAgergarActionPerformed
        
    private void tbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbEliminarActionPerformed
       String cedula = JOptionPane.showInputDialog("Ingrese la cedula a eliminar: ");
        int confirm = JOptionPane.showConfirmDialog(this, "Seguro que desea eliminar el registro: ");
        if (confirm == 0) {
            this.lista.Eliminarxcedula(cedula);
        }
    }//GEN-LAST:event_tbEliminarActionPerformed
    
    private void tbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBuscarActionPerformed
        Profesor p;
        String cedula = JOptionPane.showInputDialog("Ingrese la cedula: ");
        try {
            limpiar();
            p = this.lista.Buscarxcedula(cedula);
            txtnombre.setText(p.getNombre());
            txtapellido.setText(p.getApellido());
            txtcedula.setText(p.getCedula());
            txtsueldo.setText(p.getSueldo());
            if (p.getAsociado().equals("Si")) {
                si.setSelected(true);
            } else {
                no.setSelected(true);
            }
            cbtitulo.setSelectedIndex(p.getTitulo());
            //check 
            if (p.getProfesionales()[0] == 1) {
                chkest.setSelected(true);
            } else {
                chkest.setSelected(false);
            }
            if (p.getProfesionales()[1] == 1) {
                chkcatU.setSelected(true);
            } else {
                chkcatU.setSelected(false);
            }
            if (p.getProfesionales()[2] == 1) {
                chkdoc.setSelected(true);
            } else {
                chkdoc.setSelected(false);
            }
            if (p.getProfesionales()[3] == 1) {
                chkdocI.setSelected(true);
            } else {
                chkdocI.setSelected(false);
            }
            if (p.getProfesionales()[4] == 1) {
                chkmed.setSelected(true);
            } else {
                chkmed.setSelected(false);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Registro no encontrado "+e);
            limpiar();
        }
    }//GEN-LAST:event_tbBuscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void limpiar() {
        txtnombre.setText(" ");
        txtapellido.setText(" ");
        txtcedula.setText(" ");
        txtsueldo.setText(" ");
        tbcolegio.clearSelection();
        cbtitulo.setSelectedIndex(0);
        chkest.setSelected(false);
        chkcatU.setSelected(false);
        chkdoc.setSelected(false);
        chkdocI.setSelected(false);
        chkmed.setSelected(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbtitulo;
    private javax.swing.JCheckBox chkcatU;
    private javax.swing.JCheckBox chkdoc;
    private javax.swing.JCheckBox chkdocI;
    private javax.swing.JCheckBox chkest;
    private javax.swing.JCheckBox chkmed;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton no;
    private javax.swing.JRadioButton si;
    private javax.swing.JButton tbAgergar;
    private javax.swing.JButton tbBuscar;
    private javax.swing.JButton tbCerrar;
    private javax.swing.JButton tbEliminar;
    private javax.swing.ButtonGroup tbcolegio;
    private javax.swing.JButton tbistar;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtsueldo;
    // End of variables declaration//GEN-END:variables
}
